/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package infraestructure;
import java.awt.Image;
import javax.swing.ImageIcon;
import org.springframework.stereotype.Component;
/**
 *
 * @author cesarvillanueva
 */
@Component
public class Login_Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login_Principal.class.getName());

    /**
     * Creates new form Login_Principal
     */
    public Login_Principal() {
 //Forzamos el estilo Nimbus para que respete los colores y diseño original del Jframe
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception e) {
        // Si hay algún problema, Java continuará con el estilo estándar sin romperse
    }

    initComponents();

    // Centra la ventana en la pantalla
    this.setLocationRelativeTo(null); 
    
    // Llamamos a la ruta o lugar donde este la imagen y usamos el método de escalado
    ajustarImagen(Logo, "/imagenes/Banner_Empresa.jpeg");

    btnregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

// Este metodo ayuda demasiado a escalar imágenes a un JLabel de forma dinámica.

private void ajustarImagen(javax.swing.JLabel label, String ruta) {
    java.awt.EventQueue.invokeLater(() -> {
        java.net.URL url = getClass().getResource(ruta);
        if (url != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);
            java.awt.Image img = icon.getImage().getScaledInstance(
                label.getWidth(), label.getHeight(), java.awt.Image.SCALE_SMOOTH
            );
            label.setIcon(new javax.swing.ImageIcon(img));
        } else {
            System.err.println("No se pudo cargar la imagen en: " + ruta);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new diseño.PanelDegradado();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(200, 200, 200));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kefa III", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIAR SESION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 370, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 300, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo Electronico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        txtContraseña.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 300, 40));

        jLabel3.setFont(new java.awt.Font("Oriya Sangam MN", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿No tienes cuenta? dale aquí ➡️");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 220, -1));

        btnIngresar.setBackground(new java.awt.Color(74, 141, 215));
        btnIngresar.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 50));

        btnregistrar.setBackground(new java.awt.Color(101, 130, 218));
        btnregistrar.setFont(new java.awt.Font("Oriya Sangam MN", 1, 13)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistrar.setText("Registrarse");
        btnregistrar.setBorder(null);
        btnregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 90, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 510));

        Logo.setMaximumSize(new java.awt.Dimension(100, 100));
        Logo.setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 0, 390, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       
        String correo = txtUsuario.getText().trim();
    String password = new String(txtContraseña.getPassword()).trim(); 

    // Validación simple de campos vacíos y mensaje
    if (correo.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete su correo y contraseña.", "Campos Vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Conectamos de manera segura con el Bean de nuestro servicio de Spring Boot
        controlador.EmpleadoService empleadoService = 
            presentation.SistemaVentasApplication.getBean(controlador.EmpleadoService.class);
        
        // Ejecutamos la autenticación
        domain.Empleados empleadoLogueado = empleadoService.autenticarEmpleado(correo, password);
        
        // Mensaje de que Bienvenida con los datos correspondientes
        javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido " + empleadoLogueado.getNombre() + " " + empleadoLogueado.getApellido(), "Inicio de Sesión Exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Redirección al módulo del administrador 
            infraestructure.Menu_Principal menu = 
            new infraestructure.Menu_Principal(empleadoLogueado);
            menu.setVisible(true);
        
        this.dispose(); // Cierra de forma limpia el Login
        
    } catch (Exception e) {
        // Salta si la contraseña es errónea o el correo no existe en la Base de Datos Postgres
       javax.swing.JOptionPane.showMessageDialog(
        this, 
        e.getClass().getName() + "\n" + e.getMessage(), 
        "Error de Autenticación", 
        javax.swing.JOptionPane.ERROR_MESSAGE
    );
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMouseClicked
        try {
        // Solicitamos de forma segura la instancia de Registro al contenedor de Spring Boot
            infraestructure.Registro_Principal registro = 
            presentation.SistemaVentasApplication.getBean(infraestructure.Registro_Principal.class);
        
        registro.setVisible(true); // Despliega la ventana de registro (que ya se centra sola)
        this.dispose();            // Cierra y limpia la pantalla actual de Login
        
    } catch (Exception e) {
        // Vía de escape tradicional en caso el arranque en frío experimente algún retraso
            infraestructure.Registro_Principal registro = new infraestructure.Registro_Principal();
        registro.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnregistrarMouseClicked
    
    private void btnregistrar(java.awt.event.ActionEvent evt) {                                             
    try {
        // Solicitamos la instancia de Registro_Principal manejada por Spring Boot
            infraestructure.Registro_Principal registro = 
            presentation.SistemaVentasApplication.getBean(infraestructure.Registro_Principal.class);
        
        registro.setVisible(true); 
        this.dispose();          
        
    } catch (Exception e) {
        // Vía alterna tradicional por si el contexto experimenta alguna anomalía
            infraestructure.Registro_Principal registro = new infraestructure.Registro_Principal();
        registro.setVisible(true);
        this.dispose();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login_Principal().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
