server.port=8085
spring.application.name=sistema_ventas

// PASOS PARA HACER LA CONEXION CON LA BASE DE DATOS POSTGRES

# 1. Direcci\u00f3n de Conexi\u00f3n a PostgreSQL (Con el nombre exacto de tu BD)
spring.datasource.url=jdbc:postgresql://localhost:5432/CegerTechnology
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Tus Credenciales de acceso locales de PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=2004

# 3. Propiedades del motor Hibernate / JPA para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. ddl-auto=update crear\u00e1 o actualizar\u00e1 todas tus entidades de forma autom\u00e1tica al iniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

# 5. Muestra las consultas SQL limpias en la consola de NetBeans para depurar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true